<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newslayouts"
 *
 * Auto generated by Extension Builder 2017-10-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Layouts for news records',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Sven Wappler',
    'author_email' => 'info@wappler.systems',
    'author_company' => 'WapplerSystems',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
            'news' => '3.2.0-6.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
